CREATE TABLE `patient` (
  `deleted_yn` bit(1) DEFAULT NULL,
  `education_type` tinyint DEFAULT NULL,
  `gender` tinyint DEFAULT NULL,
  `guardian_relationship_type` tinyint DEFAULT NULL,
  `value` date DEFAULT NULL,
  `created_at` datetime(6) DEFAULT NULL,
  `id` bigint NOT NULL AUTO_INCREMENT,
  `modified_at` datetime(6) DEFAULT NULL,
  `organization_id` bigint DEFAULT NULL,
  `created_by` varchar(255) DEFAULT NULL,
  `device_serial_number` varchar(255) DEFAULT NULL,
  `guardian_name` varchar(255) DEFAULT NULL,
  `guardian_phone` varchar(255) DEFAULT NULL,
  `medical_record_number` varchar(255) DEFAULT NULL,
  `modified_by` varchar(255) DEFAULT NULL,
  `name` varchar(255) DEFAULT NULL,
  `phone` varchar(255) DEFAULT NULL,
  `title` varchar(255) DEFAULT NULL,
  `cog_level_type` varchar(100) DEFAULT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `patient_chk_1` CHECK ((`education_type` between 0 and 5)),
  CONSTRAINT `patient_chk_2` CHECK ((`gender` between 0 and 2)),
  CONSTRAINT `patient_chk_3` CHECK ((`guardian_relationship_type` between 0 and 4))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
